import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */

public class OneOfEachStats {
	public static void main (String[] args) {
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
        	Random generator = new Random(seed); 
 
		int sumOfChildren = 0;
		int numberOf2Children = 0;
		int numberOf3Children = 0;
		int numberOf4OrMoreChildren = 0;		

	for (int i =0; i < T; i++) {
		
		boolean boy = false;
		boolean girl = false;
		int count = 0;

		while  (!(girl && boy)) {
			double rnd = generator.nextDouble();

			if (rnd < 0.5) {
			boy = true;
			}
		
			else {
			girl = true;
			} 	
		count++;	
		}
		
		sumOfChildren += count;

		if (count == 2) {
			numberOf2Children++;
		}	

		else {
			if (count == 3) {
				numberOf3Children++;
			}

			else {
				numberOf4OrMoreChildren++;
			}

	
		}
	}
	
	
	double average = ((double)(sumOfChildren)/(double)(T));
	System.out.println("Average: " + average + " children to get at least one of each gender.");
	System.out.println("Number of families with 2 children: " + numberOf2Children);
	System.out.println("Number of families with 3 children: " + numberOf3Children);
	System.out.println("Number of families with 4 or more children: " + numberOf4OrMoreChildren);
	
	String maxStr = "The most common number of children is ";

	int max = Math.max(Math.max(numberOf2Children, numberOf3Children),numberOf4OrMoreChildren);

	if (max == numberOf2Children ) {
	maxStr = maxStr + "2.";	
	}	
	
	else {
		if (max == numberOf3Children ) {
		maxStr = maxStr + "3.";	
		}
		
		else {
		maxStr = maxStr + "4 or more.";	
		}
	}
	
	System.out.println(maxStr);


	}
}

		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.